codecov:
  # no notifications set up
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  # thresholds for red to green color coding
  range: '10...80'

  status:
    project:
      default:
        # compares coverage to the base branch
        target: auto
        # if it drops by 10%, send a fail status
        threshhold: 15%
        # only send statuses for prs, not all commits
        base: pr
    patch: no
    changes: no

comment: off
