version: 2
jobs:
  build:
    working_directory: ~/desktop/desktop
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    macos:
      xcode: '9.3.0'
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ .Branch }}-
        - yarn-packages-v1-
    - run: yarn install --force
    - save_cache:
        key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
        - vendor/bundle
        - .eslintcache
        - ~/.electron
        - ~/Library/Caches/Yarn/v1
        - ./node_modules
    - run: yarn lint
    - run: yarn validate-changelog
    - run: yarn build:prod
    - run: yarn test:setup
    - run: yarn test
    - run: find $HOME/Library/Developer/Xcode/DerivedData -name '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; || true
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
