name: Testing Win32

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 12.8.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install and build dependencies
        run: yarn
      - name: test setup
      - name: Build production app
        run: yarn build:prod
        run: yarn test:setup
      - name: test
        run: yarn test
        timeout-minutes: 5
